# Generated by Django 5.2.5 on 2025-11-18 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('especialidad', models.CharField(max_length=100)),
                ('biografia', models.TextField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='especialistas/')),
                ('dias_laborales', models.CharField(default='Lunes, Martes, Miercoles, Jueves, Viernes', help_text='Ej: Lunes, Martes, Miercoles', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duracion_minutos', models.PositiveIntegerField(default=60)),
                ('es_activo', models.BooleanField(default=True)),
                ('especialistas_aptos', models.ManyToManyField(related_name='servicios_ofrecidos', to='clinicapp.especialista')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField(editable=False)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Confirmación'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('COMPLETADA', 'Completada')], default='PENDIENTE', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_reservadas', to=settings.AUTH_USER_MODEL)),
                ('especialista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas_agendadas', to='clinicapp.especialista')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinicapp.servicio')),
            ],
            options={
                'unique_together': {('especialista', 'fecha_inicio', 'hora_inicio')},
            },
        ),
    ]
