# Generated by Django 5.2.5 on 2025-11-19 00:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('clinicapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
            ],
        ),
        migrations.AddField(
            model_name='cita',
            name='notas',
            field=models.TextField(blank=True, null=True, verbose_name='Notas de la visita o motivo de cancelación'),
        ),
    ]
