# Generated by Django 5.2.5 on 2025-11-23 17:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicapp', '0004_customuser_remove_servicio_especialistas_aptos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Servicio')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Precio Estimado')),
            ],
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido')),
                ('specialty', models.CharField(max_length=100, verbose_name='Especialidad Principal')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha de la Cita')),
                ('time', models.TimeField(default=django.utils.timezone.now, verbose_name='Hora de la Cita')),
                ('status', models.CharField(choices=[('P', 'Pendiente'), ('C', 'Confirmada'), ('X', 'Cancelada')], default='P', max_length=1, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Paciente')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicapp.service', verbose_name='Servicio')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicapp.specialist', verbose_name='Especialista')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'unique_together': {('specialist', 'date', 'time')},
            },
        ),
        migrations.DeleteModel(
            name='Cita',
        ),
        migrations.DeleteModel(
            name='Servicio',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
