# Generated by Django 5.2.5 on 2025-11-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicapp', '0005_service_specialist_remove_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Precio Final Cobrado'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='¿Pagada?'),
        ),
    ]
